layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
    facebook: shakthik26
    linkedin: sakthi-kumarr
    medium: '@sakthik26'
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # youtube: your_username
  # vk: your_username